import "server-only";

import { getRepoRootDoc } from "./docs";

export type KpiStatus = "Strong" | "Done" | "Partial" | "Weak" | "Not Started";

export interface KpiEntry {
  ref: number;
  component: string;
  kpi: string; // e.g. "C1-SC1"
  subComponent: string;
  phase: string; // "Phase 1" etc.
  status: KpiStatus;
  weHave: string;
  missing: string;
}

/**
 * Parse `BACKLOG.md` at the repo root into a typed list of KPI rows.
 *
 * The MD is generated by `scripts/build-backlog.mjs`. The shape parsed
 * here follows that generator's emit pattern:
 *
 *   ## 1. Foundation & Security
 *
 *   ### 🟡 C1-SC1 — Cloud environment provisioning  *(Phase 1)*
 *
 *   ... | **Status** | **Partial** |
 *   | **What we have** | ... |
 *   | **What's missing** | ... |
 */
export async function parseBacklog(): Promise<KpiEntry[]> {
  const md = await getRepoRootDoc("BACKLOG.md");
  if (!md) return [];

  const entries: KpiEntry[] = [];

  // First split into ## sections — one per component.
  const sections = md.split(/\n## (\d+)\.\s+/).slice(1);
  for (let i = 0; i < sections.length; i += 2) {
    const ref = Number(sections[i]);
    const body = sections[i + 1] ?? "";
    const componentName = body.split("\n")[0].trim();

    // Each ### inside this section = one KPI sub-component
    const kpiBlocks = body.split(/\n### /).slice(1);
    for (const block of kpiBlocks) {
      const head = block.split("\n")[0];
      // Head looks like: 🟡 C1-SC1 — Cloud environment provisioning  *(Phase 1)*
      const m = head.match(
        /^(?:\S+\s+)?(C\d+-SC\d+)\s+—\s+(.+?)\s*\*\((Phase \d+)\)\*/,
      );
      if (!m) continue;
      const [, kpi, subComponent, phase] = m;

      const status =
        (block.match(/\|\s*\*\*Status\*\*\s*\|\s*\*\*([^*|]+)\*\*\s*\|/)?.[1].trim() as
          | KpiStatus
          | undefined) ?? "Not Started";
      const weHave =
        block
          .match(/\|\s*\*\*What we have\*\*\s*\|\s*([^|]+)/)?.[1]
          .trim()
          .replace(/\s+$/, "") ?? "";
      const missing =
        block
          .match(/\|\s*\*\*What's missing\*\*\s*\|\s*([^|]+)/)?.[1]
          .trim()
          .replace(/\s+$/, "") ?? "";

      entries.push({
        ref,
        component: componentName,
        kpi,
        subComponent,
        phase,
        status,
        weHave,
        missing,
      });
    }
  }
  return entries;
}

export type StatusBucket = "green" | "yellow" | "orange" | "red";

export function bucketFor(s: KpiStatus): StatusBucket {
  if (s === "Strong" || s === "Done") return "green";
  if (s === "Partial") return "yellow";
  if (s === "Weak") return "orange";
  return "red";
}

export interface BacklogSummary {
  total: number;
  green: number;
  yellow: number;
  orange: number;
  red: number;
  byComponent: { ref: number; component: string; total: number; green: number }[];
}

export async function getBacklogSummary(): Promise<BacklogSummary> {
  const rows = await parseBacklog();
  const sum: BacklogSummary = {
    total: rows.length,
    green: 0,
    yellow: 0,
    orange: 0,
    red: 0,
    byComponent: [],
  };
  const byComp = new Map<string, { ref: number; component: string; total: number; green: number }>();
  for (const r of rows) {
    sum[bucketFor(r.status)]++;
    const k = `${r.ref}|${r.component}`;
    if (!byComp.has(k)) byComp.set(k, { ref: r.ref, component: r.component, total: 0, green: 0 });
    const entry = byComp.get(k)!;
    entry.total++;
    if (bucketFor(r.status) === "green") entry.green++;
  }
  sum.byComponent = [...byComp.values()].sort((a, b) => a.ref - b.ref);
  return sum;
}
